version: "3.9"

services:
  db:
    image: postgres:16
    container_name: wafer-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: wafer
      POSTGRES_PASSWORD: waferpass
      POSTGRES_DB: waferdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: